'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Evaluar_Plano
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''txt_m2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_m2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_ilumina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_ilumina As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_tc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_iluminaue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_iluminaue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_tcue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tcue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drp_ambiente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_ambiente As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txt_bocatc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_bocatc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_bocailumina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_bocailumina As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_bocailuminaue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_bocailuminaue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_bocatcue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_bocatcue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_evaluarplano control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_evaluarplano As Global.System.Web.UI.WebControls.Button
End Class
