'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Home
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''lnk_login control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk_login As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''frm_backupyrestore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm_backupyrestore As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''frm_idioma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm_idioma As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''frm_bitacora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm_bitacora As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''frm_cifrado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm_cifrado As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''frm_Bocamercado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm_Bocamercado As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''frm_evaluardistancia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm_evaluardistancia As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnk_evalplano control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk_evalplano As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''frm_creacionpresatenc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm_creacionpresatenc As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''frm_creacionpresumodtec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm_creacionpresumodtec As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''frm_armadopresupuestomodcome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm_armadopresupuestomodcome As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''frm_especificarfechaproy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm_especificarfechaproy As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''frm_cierreproy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm_cierreproy As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''frm_generaciongraf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm_generaciongraf As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''frm_generacionpresu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm_generacionpresu As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''frm_generacionserv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm_generacionserv As Global.System.Web.UI.WebControls.LinkButton
End Class
