'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class web_gestbocamer
    
    '''<summary>
    '''lbl_precioingresado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_precioingresado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''num_bocamercado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents num_bocamercado As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbl_bocamercado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_bocamercado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_bocamercado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_bocamercado As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbl_bocaempresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_bocaempresa As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_bocaempresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_bocaempresa As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbl_bocaextraordinaria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_bocaextraordinaria As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_bocaextraordinaria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_bocaextraordinaria As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_guardarprboca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_guardarprboca As Global.System.Web.UI.WebControls.Button
End Class
