'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class web_evaluplano
    
    '''<summary>
    '''lbl_numeroambiente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_numeroambiente As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_numeroambiente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_numeroambiente As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbl_tipoambiente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_tipoambiente As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''drp_ambiente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_ambiente As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbl_m2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_m2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_m2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_m2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbl_circiluminacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_circiluminacion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_circiluminacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_circiluminacion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chk_circiluminacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_circiluminacion As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lbl_circtomacorriente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_circtomacorriente As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_circtomacorriente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_circtomacorriente As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chk_circtomacorriente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_circtomacorriente As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lbl_circiluminaespecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_circiluminaespecial As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_circiluminaespecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_circiluminaespecial As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chk_circiluminaespecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_circiluminaespecial As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lbl_circtomacorrienteespecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_circtomacorrienteespecial As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_circtomacorrienteespecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_circtomacorrienteespecial As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chk_circtomacorrienteespecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_circtomacorrienteespecial As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lbl_cantcirciluminacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_cantcirciluminacion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_cantcirciluminacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_cantcirciluminacion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbl_cantcirctomacorriente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_cantcirctomacorriente As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_cantcirctomacorriente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_cantcirctomacorriente As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbl_cantcirciluminaespecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_cantcirciluminaespecial As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_cantcirciluminaespecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_cantcirciluminaespecial As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbl_cantcirctomacorrienteespecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_cantcirctomacorrienteespecial As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_cantcirctomacorrienteespecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_cantcirctomacorrienteespecial As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_nuevo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_nuevo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnambiente_agregar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnambiente_agregar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_evaluarplano control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_evaluarplano As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_guardardibujo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_guardardibujo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_cancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cancelar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''dtg_ambientes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtg_ambientes As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lbl_ambiente_anotacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ambiente_anotacion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dtg_evaluarplano control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtg_evaluarplano As Global.System.Web.UI.WebControls.GridView
End Class
