'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class web_reporte_seleccion
    
    '''<summary>
    '''lbl_codpresupuesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_codpresupuesto As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmb_presupuesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_presupuesto As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btn_cargar_presupuesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cargar_presupuesto As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''chk_valormaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_valormaterial As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chk_valormano control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_valormano As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chk_valortrabajo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_valortrabajo As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chk_valorotros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_valorotros As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chk_valorsegvida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_valorsegvida As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chk_materiales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_materiales As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chk_artefactos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_artefactos As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chk_trabajos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_trabajos As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chk_porcluz control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_porcluz As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''btn_exportarrep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_exportarrep As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_cancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cancelar As Global.System.Web.UI.WebControls.Button
End Class
