'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class web_creacionatcte
    
    '''<summary>
    '''lbl_codpresupuesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_codpresupuesto As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmb_presupuesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_presupuesto As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btn_cargar_presupuesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cargar_presupuesto As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lbl_dnicuit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_dnicuit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_dnicuit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_dnicuit As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_buscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_buscar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lbl_nombre_razonsocial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_nombre_razonsocial As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_nombre_razonsocial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_nombre_razonsocial As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LBL_Parti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_Parti As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbx_parti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_parti As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LBL_Loca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_Loca As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbx_localidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_localidad As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LBL_Calle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_Calle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_calle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_calle As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LBL_Altura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_Altura As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_altura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_altura As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbl_piso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_piso As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_piso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_piso As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbl_depto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_depto As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_depto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_depto As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CHK_Country control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CHK_Country As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lbl_dibujotecnico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_dibujotecnico As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''drp_dibujo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_dibujo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btn_verdibujo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_verdibujo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_nuevopresu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_nuevopresu As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_guardarpresu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_guardarpresu As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_cancelarpresu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cancelarpresu As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''dtg_ambientes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtg_ambientes As Global.System.Web.UI.WebControls.GridView
End Class
