'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class web_Presupuestovalor
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmb_presupuesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_presupuesto As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btn_cargar_presupuesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cargar_presupuesto As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''grp_desdedonde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grp_desdedonde As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LBL_Parti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_Parti As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbx_parti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_parti As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LBL_Loca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_Loca As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbx_localidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_localidad As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''grp_especificacionesadicionales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grp_especificacionesadicionales As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''chk_actuaindice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_actuaindice As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chk_preciosegvida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_preciosegvida As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lbl_precsegvida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_precsegvida As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_valorseg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_valorseg As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chk_viatico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_viatico As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lbl_precviatico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_precviatico As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_valorvia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_valorvia As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chk_cobroadel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_cobroadel As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lbl_porcadelanto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_porcadelanto As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_poradelanto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_poradelanto As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_calcvaltot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_calcvaltot As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_guardarpresucom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_guardarpresucom As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_cancelarprtec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cancelarprtec As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''grd_presupuesto_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_presupuesto_final As Global.System.Web.UI.WebControls.GridView
End Class
