'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class web_usuario
    
    '''<summary>
    '''lbl_username control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_username As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_usuario As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbl_password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_password As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_password As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chk_bloqueado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_bloqueado As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lbl_idioma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_idioma As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''drp_idioma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_idioma As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbl_roles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_roles As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''drp_roles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_roles As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lst_users control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lst_users As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''btn_nuevous control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_nuevous As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_guardarus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_guardarus As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_eliminar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_eliminar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_cancelarus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cancelarus As Global.System.Web.UI.WebControls.Button
End Class
