'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class web_gestartefactos
    
    '''<summary>
    '''lbl_artefacto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_artefacto As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_descripcionartefacto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_descripcionartefacto As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbl_relacionboca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_relacionboca As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''num_relacionboca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents num_relacionboca As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbl_precio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_precio As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''num_precio2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents num_precio2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_nuevoarte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_nuevoarte As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_guardararte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_guardararte As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_cancelararte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cancelararte As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''dtg_artefacto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtg_artefacto As Global.System.Web.UI.WebControls.GridView
End Class
