'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class web_bitacora
    
    '''<summary>
    '''chk_fechadesde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_fechadesde As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''dtp_fechadesde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtp_fechadesde As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chk_fechahasta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_fechahasta As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''dtp_fechahasta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtp_fechahasta As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chk_nombredeusuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_nombredeusuario As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbx_usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_usuario As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''chk_codigodeevento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_codigodeevento As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbx_codigoevento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_codigoevento As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btn_buscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_buscar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GVGrillaEventos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVGrillaEventos As Global.System.Web.UI.WebControls.GridView
End Class
